### ISSUE TITLE
Large size image having optimization issues

### ISSUE THREAD

**Issue by kevalvavaliya** [Bauddhik-Geeks/Localens#1]
We are converting image into base64 and then store the string into the database so if the size of image is more it takes much time to store and retrieve the string from and to the database.

**Comment by BashCache** [comment]
Hi, I would like to work on this. I would like to know if we can use any cloud services to store images so that we can store the path name alone in the database or will storing the image as BLOB type be better than base64 encoding.

**Comment by kevalvavaliya** [comment]
I think we should go with storing BLOB rather then using cloud services for now

**Comment by BashCache** [comment]
Hi, can I try working on this issue?

**Comment by kevalvavaliya** [comment]
Go Ahead
 Make sure to join the organization and discord server first so that your contribution is counted as hacktoberfest accepted.😊

Organization link👉 https://github.com/Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks
Discord server link 👉 https://join.bauddhikgeeks.tech/

**Comment by neel0976** [comment]
Hey I could try to store it into IPFS but loading it may take some time can try this, if you can assign me this one if no one is working on it?
